variable "name" {}
variable "vpc" {}
variable "bastion_sg" {}
variable "keypair" {}
variable "subnet_id" {}
variable "private-key" {}
variable "nexus-ip" {}
variable "nr-key" {}
variable "nr-acc-id" {}